/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class Configurar_InformacionEmpresaClienteDelSoftware extends javax.swing.JDialog {

    /**
     * Creates new form Configurar_InformacionEmpresaClienteDelSoftware
     */
    public Configurar_InformacionEmpresaClienteDelSoftware(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cajaCelular = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cajaTelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaUbicacion = new javax.swing.JTextField();
        cajaDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaNit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cajaRazonSocial = new javax.swing.JTextField();
        botonOk = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cajaCelular.setBackground(new java.awt.Color(255, 255, 255));
        cajaCelular.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCelular.setForeground(new java.awt.Color(204, 204, 204));
        cajaCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCelular.setText("Celular de contacto");
        cajaCelular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 280, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Celular");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 120, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Telefono");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 120, 30));

        cajaTelefono.setBackground(new java.awt.Color(255, 255, 255));
        cajaTelefono.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaTelefono.setForeground(new java.awt.Color(204, 204, 204));
        cajaTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTelefono.setText("Telefono de contacto");
        cajaTelefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 280, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Ubicación");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 120, 30));

        cajaUbicacion.setBackground(new java.awt.Color(255, 255, 255));
        cajaUbicacion.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaUbicacion.setForeground(new java.awt.Color(204, 204, 204));
        cajaUbicacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaUbicacion.setText("Departamento - Municipio");
        cajaUbicacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 280, 30));

        cajaDireccion.setBackground(new java.awt.Color(255, 255, 255));
        cajaDireccion.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaDireccion.setForeground(new java.awt.Color(204, 204, 204));
        cajaDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaDireccion.setText("Direccion Empresa");
        cajaDireccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 280, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Dirección");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 120, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nit.");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, 30));

        cajaNit.setBackground(new java.awt.Color(255, 255, 255));
        cajaNit.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNit.setForeground(new java.awt.Color(204, 204, 204));
        cajaNit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNit.setText("Nit. la empresa - Cedula representante legal");
        cajaNit.setToolTipText("");
        cajaNit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 280, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Razón social");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 120, 30));

        cajaRazonSocial.setBackground(new java.awt.Color(255, 255, 255));
        cajaRazonSocial.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaRazonSocial.setForeground(new java.awt.Color(204, 204, 204));
        cajaRazonSocial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaRazonSocial.setText("Nombre de la Empresa");
        cajaRazonSocial.setToolTipText("");
        cajaRazonSocial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 280, 30));

        botonOk.setBackground(new java.awt.Color(255, 255, 255));
        botonOk.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonOk.setForeground(new java.awt.Color(0, 0, 0));
        botonOk.setText("OK");
        botonOk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOk.setFocusPainted(false);
        jPanel1.add(botonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 70, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Configurar Información de la Empresa");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 70));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/fondo-de-colores-lisos.jpg"))); // NOI18N
        labelFondo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configurar_InformacionEmpresaClienteDelSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configurar_InformacionEmpresaClienteDelSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configurar_InformacionEmpresaClienteDelSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configurar_InformacionEmpresaClienteDelSoftware.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configurar_InformacionEmpresaClienteDelSoftware dialog = new Configurar_InformacionEmpresaClienteDelSoftware(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonOk;
    public javax.swing.JTextField cajaCelular;
    public javax.swing.JTextField cajaDireccion;
    public javax.swing.JTextField cajaNit;
    public javax.swing.JTextField cajaRazonSocial;
    public javax.swing.JTextField cajaTelefono;
    public javax.swing.JTextField cajaUbicacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFondo;
    // End of variables declaration//GEN-END:variables
}
