/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class ConsultarProducto extends javax.swing.JDialog {

    /**
     * Creates new form ConsultarClientes
     */
    public ConsultarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarTodoProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductosConsultados = new javax.swing.JTable();
        botonBuscarPorEleccion = new javax.swing.JButton();
        cajaBuscar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboElegirFormaBusqueda = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaCantidadStock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaPrecio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cajaProveedor = new javax.swing.JTextField();
        dateChooserFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cajaCodigodeBarras = new javax.swing.JTextField();
        cajaLaboratorio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTAR MEDICAMENTOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 830, 40));

        botonBuscarTodoProducto.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarTodoProducto.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarTodoProducto.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscarTodoProducto.setText("Mostrar todos");
        botonBuscarTodoProducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarTodoProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarTodoProducto.setFocusPainted(false);
        botonBuscarTodoProducto.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscarTodoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 110, 30));

        tablaProductosConsultados.setBackground(new java.awt.Color(255, 255, 255));
        tablaProductosConsultados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaProductosConsultados.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        tablaProductosConsultados.setForeground(new java.awt.Color(0, 0, 0));
        tablaProductosConsultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductosConsultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 880, 170));

        botonBuscarPorEleccion.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarPorEleccion.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarPorEleccion.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscarPorEleccion.setText("Buscar");
        botonBuscarPorEleccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarPorEleccion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarPorEleccion.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscarPorEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 80, -1));

        cajaBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaBuscar.setForeground(new java.awt.Color(204, 204, 204));
        cajaBuscar.setText("Digite los datos del medicamento");
        cajaBuscar.setBorder(null);
        cajaBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 240, 30));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Buscar por : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 30));

        comboElegirFormaBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboElegirFormaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 160, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 640, 50));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre :");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 30));

        cajaNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombre.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombre.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombre.setBorder(null);
        jPanel1.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 250, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Stock :");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 100, 30));

        cajaCantidadStock.setBackground(new java.awt.Color(255, 255, 255));
        cajaCantidadStock.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCantidadStock.setForeground(new java.awt.Color(102, 102, 102));
        cajaCantidadStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCantidadStock.setBorder(null);
        jPanel1.add(cajaCantidadStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 120, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio :");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 100, 30));

        cajaPrecio.setBackground(new java.awt.Color(255, 255, 255));
        cajaPrecio.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaPrecio.setForeground(new java.awt.Color(102, 102, 102));
        cajaPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaPrecio.setBorder(null);
        jPanel1.add(cajaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 250, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Laboratorio :");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 140, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Proveedor :");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 140, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Codigo barras :");
        jLabel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 150, 30));

        cajaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        cajaProveedor.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaProveedor.setForeground(new java.awt.Color(102, 102, 102));
        cajaProveedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaProveedor.setBorder(null);
        jPanel1.add(cajaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 280, 30));

        dateChooserFechaVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        dateChooserFechaVencimiento.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(dateChooserFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 160, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Fecha Vencimiento :");
        jLabel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 190, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        jScrollPane2.setViewportView(TextAreaDescripcion);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 280, 70));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descripción :");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 150, 30));

        cajaCodigodeBarras.setBackground(new java.awt.Color(255, 255, 255));
        cajaCodigodeBarras.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCodigodeBarras.setForeground(new java.awt.Color(102, 102, 102));
        cajaCodigodeBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCodigodeBarras.setBorder(null);
        jPanel1.add(cajaCodigodeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 280, 30));

        cajaLaboratorio.setBackground(new java.awt.Color(255, 255, 255));
        cajaLaboratorio.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaLaboratorio.setForeground(new java.awt.Color(102, 102, 102));
        cajaLaboratorio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaLaboratorio.setBorder(null);
        jPanel1.add(cajaLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 280, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/consultas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 506));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarProducto dialog = new ConsultarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TextAreaDescripcion;
    public javax.swing.JButton botonBuscarPorEleccion;
    public javax.swing.JButton botonBuscarTodoProducto;
    public javax.swing.JTextField cajaBuscar;
    public javax.swing.JTextField cajaCantidadStock;
    public javax.swing.JTextField cajaCodigodeBarras;
    public javax.swing.JTextField cajaLaboratorio;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JTextField cajaPrecio;
    public javax.swing.JTextField cajaProveedor;
    public javax.swing.JComboBox<String> comboElegirFormaBusqueda;
    public com.toedter.calendar.JDateChooser dateChooserFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaProductosConsultados;
    // End of variables declaration//GEN-END:variables
}
