/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class ConsultarClientes extends javax.swing.JDialog {

    /**
     * Creates new form ConsultarClientes
     */
    public ConsultarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonBuscarTodoCliente = new javax.swing.JButton();
        cajaBuscarPorCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cajaApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaCelular = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaDireccion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientesConsultados = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CONSULTAR CLIENTES");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 570, 40));

        botonBuscarTodoCliente.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarTodoCliente.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarTodoCliente.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscarTodoCliente.setText("Listar todos");
        botonBuscarTodoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarTodoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarTodoCliente.setFocusPainted(false);
        botonBuscarTodoCliente.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscarTodoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 30));

        cajaBuscarPorCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscarPorCedula.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaBuscarPorCedula.setForeground(new java.awt.Color(204, 204, 204));
        cajaBuscarPorCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaBuscarPorCedula.setText("Filtrar por Cedula");
        cajaBuscarPorCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaBuscarPorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre ");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 30));

        cajaNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombre.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombre.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombre.setBorder(null);
        jPanel1.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 330, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 90, 30));

        cajaApellido.setBackground(new java.awt.Color(255, 255, 255));
        cajaApellido.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaApellido.setForeground(new java.awt.Color(102, 102, 102));
        cajaApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaApellido.setBorder(null);
        jPanel1.add(cajaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 330, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cedula");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        cajaCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaCedula.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCedula.setForeground(new java.awt.Color(102, 102, 102));
        cajaCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCedula.setBorder(null);
        jPanel1.add(cajaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 330, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Correo");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 90, 30));

        cajaCorreo.setBackground(new java.awt.Color(255, 255, 255));
        cajaCorreo.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCorreo.setForeground(new java.awt.Color(102, 102, 102));
        cajaCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCorreo.setBorder(null);
        jPanel1.add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 330, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Celular");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 30));

        cajaCelular.setBackground(new java.awt.Color(255, 255, 255));
        cajaCelular.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCelular.setForeground(new java.awt.Color(102, 102, 102));
        cajaCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCelular.setBorder(null);
        jPanel1.add(cajaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 330, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Dirección");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 90, 30));

        cajaDireccion.setBackground(new java.awt.Color(255, 255, 255));
        cajaDireccion.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaDireccion.setForeground(new java.awt.Color(102, 102, 102));
        cajaDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaDireccion.setBorder(null);
        jPanel1.add(cajaDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 330, 30));

        tablaClientesConsultados.setBackground(new java.awt.Color(255, 255, 255));
        tablaClientesConsultados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaClientesConsultados.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        tablaClientesConsultados.setForeground(new java.awt.Color(0, 0, 0));
        tablaClientesConsultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaClientesConsultados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 860, 180));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Filtrar por cedula");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 100, 20));

        botonSalir.setBackground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("Salir");
        botonSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.setFocusPainted(false);
        jPanel1.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/consultas.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 506));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarClientes dialog = new ConsultarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonBuscarTodoCliente;
    public javax.swing.JButton botonSalir;
    public javax.swing.JTextField cajaApellido;
    public javax.swing.JTextField cajaBuscarPorCedula;
    public javax.swing.JTextField cajaCedula;
    public javax.swing.JTextField cajaCelular;
    public javax.swing.JTextField cajaCorreo;
    public javax.swing.JTextField cajaDireccion;
    public javax.swing.JTextField cajaNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaClientesConsultados;
    // End of variables declaration//GEN-END:variables
}
