/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class GestionarLaboratorio extends javax.swing.JDialog {

    /**
     * Creates new form CrearCliente
     */
    public GestionarLaboratorio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombreNuevo = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        cajaNombreEditado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cajaNombreBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelNombreEditado = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        labelMuestraLaboratorio = new javax.swing.JLabel();
        labelLaboratorioSelecionado = new javax.swing.JLabel();
        labelLaboratorioSelecionado1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIÓN DE LABORATORIOS");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 390, 40));

        cajaNombreNuevo.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreNuevo.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombreNuevo.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombreNuevo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombreNuevo.setBorder(null);
        jPanel1.add(cajaNombreNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 330, 30));

        botonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscar.setFocusPainted(false);
        botonBuscar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 80, -1));

        botonCrear.setBackground(new java.awt.Color(255, 255, 255));
        botonCrear.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(102, 102, 102));
        botonCrear.setText("Crear");
        botonCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrear.setFocusPainted(false);
        botonCrear.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 80, -1));

        botonEditar.setBackground(new java.awt.Color(255, 255, 255));
        botonEditar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(102, 102, 102));
        botonEditar.setText("Editar");
        botonEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusPainted(false);
        botonEditar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(102, 102, 102));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setFocusPainted(false);
        botonEliminar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, -1));

        cajaNombreEditado.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreEditado.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombreEditado.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombreEditado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombreEditado.setToolTipText("");
        cajaNombreEditado.setBorder(null);
        jPanel1.add(cajaNombreEditado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 390, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo Laboratorio");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 650, 40));

        cajaNombreBuscar.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreBuscar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombreBuscar.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombreBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombreBuscar.setToolTipText("");
        cajaNombreBuscar.setBorder(null);
        jPanel1.add(cajaNombreBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 330, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Nombre :");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 100, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Gestionar Laboratorio");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 640, 40));

        labelNombreEditado.setBackground(new java.awt.Color(255, 255, 255));
        labelNombreEditado.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        labelNombreEditado.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreEditado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreEditado.setText("Nuevo nombre :");
        labelNombreEditado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelNombreEditado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 150, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(102, 102, 102));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 30));

        labelMuestraLaboratorio.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        labelMuestraLaboratorio.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(labelMuestraLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 360, 40));

        labelLaboratorioSelecionado.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelLaboratorioSelecionado.setForeground(new java.awt.Color(102, 102, 102));
        labelLaboratorioSelecionado.setText("Laboratorio");
        jPanel1.add(labelLaboratorioSelecionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 360, -1, 30));

        labelLaboratorioSelecionado1.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelLaboratorioSelecionado1.setForeground(new java.awt.Color(102, 102, 102));
        labelLaboratorioSelecionado1.setText("selecionado Ahora :");
        jPanel1.add(labelLaboratorioSelecionado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 380, -1, 20));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Nombre :");
        jLabel12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ingresarRegistros.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarLaboratorio dialog = new GestionarLaboratorio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonCrear;
    public javax.swing.JButton botonEditar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JTextField cajaNombreBuscar;
    public javax.swing.JTextField cajaNombreEditado;
    public javax.swing.JTextField cajaNombreNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelLaboratorioSelecionado;
    public javax.swing.JLabel labelLaboratorioSelecionado1;
    public javax.swing.JLabel labelMuestraLaboratorio;
    public javax.swing.JLabel labelNombreEditado;
    // End of variables declaration//GEN-END:variables
}
