/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class GestionarProveedor extends javax.swing.JDialog {

    /**
     * Creates new form CrearCliente
     */
    public GestionarProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaApellido = new javax.swing.JTextField();
        cajaCedula = new javax.swing.JTextField();
        cajaCelular = new javax.swing.JTextField();
        cajaCorreo = new javax.swing.JTextField();
        cajaNombreEmpresa = new javax.swing.JTextField();
        botonBuscarPorCedula = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cajaBuscarPorCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cajaTelEmpresa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cajaDirEmpresa = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIÓN DE PROVEEDORES");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 370, 40));

        cajaNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombre.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombre.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombre.setBorder(null);
        jPanel1.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 220, 30));

        cajaApellido.setBackground(new java.awt.Color(255, 255, 255));
        cajaApellido.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaApellido.setForeground(new java.awt.Color(102, 102, 102));
        cajaApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaApellido.setBorder(null);
        jPanel1.add(cajaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 220, 30));

        cajaCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaCedula.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCedula.setForeground(new java.awt.Color(102, 102, 102));
        cajaCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCedula.setBorder(null);
        jPanel1.add(cajaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 220, 30));

        cajaCelular.setBackground(new java.awt.Color(255, 255, 255));
        cajaCelular.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCelular.setForeground(new java.awt.Color(102, 102, 102));
        cajaCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCelular.setBorder(null);
        jPanel1.add(cajaCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 220, 30));

        cajaCorreo.setBackground(new java.awt.Color(255, 255, 255));
        cajaCorreo.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCorreo.setForeground(new java.awt.Color(102, 102, 102));
        cajaCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCorreo.setBorder(null);
        jPanel1.add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 220, 30));

        cajaNombreEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombreEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombreEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombreEmpresa.setBorder(null);
        jPanel1.add(cajaNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 220, 30));

        botonBuscarPorCedula.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarPorCedula.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarPorCedula.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscarPorCedula.setText("Buscar Por Cedula");
        botonBuscarPorCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarPorCedula.setFocusPainted(false);
        botonBuscarPorCedula.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscarPorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 140, -1));

        botonCrear.setBackground(new java.awt.Color(255, 255, 255));
        botonCrear.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(102, 102, 102));
        botonCrear.setText("Crear");
        botonCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrear.setFocusPainted(false);
        botonCrear.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        botonEditar.setBackground(new java.awt.Color(255, 255, 255));
        botonEditar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(102, 102, 102));
        botonEditar.setText("Editar");
        botonEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusPainted(false);
        botonEditar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(102, 102, 102));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setFocusPainted(false);
        botonEliminar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre :");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Apellido :");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 90, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Correo :");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 90, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Cedula :");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Celular :");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 90, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Empresa :");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 90, 30));

        cajaBuscarPorCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscarPorCedula.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaBuscarPorCedula.setForeground(new java.awt.Color(102, 102, 102));
        cajaBuscarPorCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaBuscarPorCedula.setBorder(null);
        jPanel1.add(cajaBuscarPorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tel emp :");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 90, 30));

        cajaTelEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaTelEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaTelEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        cajaTelEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTelEmpresa.setBorder(null);
        jPanel1.add(cajaTelEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Dir. emp :");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 90, 30));

        cajaDirEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        cajaDirEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaDirEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        cajaDirEmpresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaDirEmpresa.setBorder(null);
        jPanel1.add(cajaDirEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 220, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(102, 102, 102));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ingresarRegistros.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarProveedor dialog = new GestionarProveedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonBuscarPorCedula;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonCrear;
    public javax.swing.JButton botonEditar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JTextField cajaApellido;
    public javax.swing.JTextField cajaBuscarPorCedula;
    public javax.swing.JTextField cajaCedula;
    public javax.swing.JTextField cajaCelular;
    public javax.swing.JTextField cajaCorreo;
    public javax.swing.JTextField cajaDirEmpresa;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JTextField cajaNombreEmpresa;
    public javax.swing.JTextField cajaTelEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
