/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Programa;

/**
 *
 * @author HP
 */
public class GestionarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form CrearUsuario2
     */
    public GestionarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        labelTipoGestionUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaPrimerNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cajaSegundoNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cajaPrimerApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajaSegundoApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cajaCedula = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cajaNickName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cajaPassword = new javax.swing.JPasswordField();
        boton_CrearEditarEliminar_Usuario = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        comboCargo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cajaCorreo = new javax.swing.JTextField();
        botonBuscarUsuarioPorCedula = new javax.swing.JButton();
        cajaBuscarPorCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTipoGestionUsuario.setBackground(new java.awt.Color(204, 204, 204));
        labelTipoGestionUsuario.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        labelTipoGestionUsuario.setForeground(new java.awt.Color(51, 51, 51));
        labelTipoGestionUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTipoGestionUsuario.setText("CREAR TU USUARIO");
        labelTipoGestionUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(labelTipoGestionUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 310, 40));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Primer Nombre :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 30));

        cajaPrimerNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaPrimerNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaPrimerNombre.setBorder(null);
        jPanel2.add(cajaPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, 30));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Segundo Nombre :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 130, 30));

        cajaSegundoNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaSegundoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaSegundoNombre.setBorder(null);
        jPanel2.add(cajaSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 170, 30));

        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Primer Apellido :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 120, 30));

        cajaPrimerApellido.setBackground(new java.awt.Color(255, 255, 255));
        cajaPrimerApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaPrimerApellido.setBorder(null);
        jPanel2.add(cajaPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, 30));

        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Segundo Apellido :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 30));

        cajaSegundoApellido.setBackground(new java.awt.Color(255, 255, 255));
        cajaSegundoApellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaSegundoApellido.setBorder(null);
        jPanel2.add(cajaSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 170, 30));

        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cedula :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 60, 30));

        cajaCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCedula.setBorder(null);
        jPanel2.add(cajaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 30));

        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Cargo :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 50, 30));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Usuario :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 70, 30));

        cajaNickName.setBackground(new java.awt.Color(255, 255, 255));
        cajaNickName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNickName.setBorder(null);
        jPanel2.add(cajaNickName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, 30));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contraseña :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 90, 30));

        cajaPassword.setBackground(new java.awt.Color(255, 255, 255));
        cajaPassword.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cajaPassword.setForeground(new java.awt.Color(0, 0, 0));
        cajaPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaPassword.setBorder(null);
        jPanel2.add(cajaPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 180, 30));

        boton_CrearEditarEliminar_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        boton_CrearEditarEliminar_Usuario.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        boton_CrearEditarEliminar_Usuario.setForeground(new java.awt.Color(0, 0, 0));
        boton_CrearEditarEliminar_Usuario.setText("Crear Usuario");
        boton_CrearEditarEliminar_Usuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_CrearEditarEliminar_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_CrearEditarEliminar_Usuario.setFocusPainted(false);
        jPanel2.add(boton_CrearEditarEliminar_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 410, 130, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setFocusPainted(false);
        jPanel2.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 410, 140, 30));

        comboCargo.setBackground(new java.awt.Color(255, 255, 255));
        comboCargo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        comboCargo.setForeground(new java.awt.Color(0, 0, 0));
        comboCargo.setBorder(null);
        jPanel2.add(comboCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 170, -1));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Correo :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 70, 30));

        cajaCorreo.setBackground(new java.awt.Color(255, 255, 255));
        cajaCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCorreo.setBorder(null);
        jPanel2.add(cajaCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 180, 30));

        botonBuscarUsuarioPorCedula.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarUsuarioPorCedula.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarUsuarioPorCedula.setForeground(new java.awt.Color(0, 0, 0));
        botonBuscarUsuarioPorCedula.setText("Buscar por Cedula");
        botonBuscarUsuarioPorCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarUsuarioPorCedula.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarUsuarioPorCedula.setFocusPainted(false);
        jPanel2.add(botonBuscarUsuarioPorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 140, 30));

        cajaBuscarPorCedula.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscarPorCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaBuscarPorCedula.setBorder(null);
        jPanel2.add(cajaBuscarPorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 30));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 650, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/inicioDeSesion.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 719, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Programa.crearUsuario=null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarUsuario dialog = new GestionarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonBuscarUsuarioPorCedula;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton boton_CrearEditarEliminar_Usuario;
    public javax.swing.JTextField cajaBuscarPorCedula;
    public javax.swing.JTextField cajaCedula;
    public javax.swing.JTextField cajaCorreo;
    public javax.swing.JTextField cajaNickName;
    public javax.swing.JPasswordField cajaPassword;
    public javax.swing.JTextField cajaPrimerApellido;
    public javax.swing.JTextField cajaPrimerNombre;
    public javax.swing.JTextField cajaSegundoApellido;
    public javax.swing.JTextField cajaSegundoNombre;
    public javax.swing.JComboBox<String> comboCargo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel labelTipoGestionUsuario;
    // End of variables declaration//GEN-END:variables
}
