/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class GestionarProducto extends javax.swing.JDialog {

    /**
     * Creates new form GestionarProducto
     */
    public GestionarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cajaNombre = new javax.swing.JTextField();
        cajaCantidadStock = new javax.swing.JTextField();
        cajaCodigodeBarras = new javax.swing.JTextField();
        botonBuscarCodigoBarras = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cajaBuscarPorCodigoBarras = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        dateChooserFechaVencimiento = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaDescripcion = new javax.swing.JTextArea();
        comboLaboratorio = new javax.swing.JComboBox<>();
        comboProveedor = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cajaPrecio = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        botonLimpiar = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelimagenUpLoad = new javax.swing.JLabel();
        labelTextoCargar = new javax.swing.JLabel();
        labelimagenNombreArchivo = new javax.swing.JLabel();
        labelEliminarImagen = new javax.swing.JLabel();
        panelimagen = new javax.swing.JPanel();
        labelNoHayImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GESTIÓN DE MEDICAMENTOS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 370, 40));

        cajaNombre.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombre.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaNombre.setForeground(new java.awt.Color(102, 102, 102));
        cajaNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombre.setBorder(null);
        jPanel1.add(cajaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 240, 30));

        cajaCantidadStock.setBackground(new java.awt.Color(255, 255, 255));
        cajaCantidadStock.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCantidadStock.setForeground(new java.awt.Color(102, 102, 102));
        cajaCantidadStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCantidadStock.setBorder(null);
        jPanel1.add(cajaCantidadStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 200, 30));

        cajaCodigodeBarras.setBackground(new java.awt.Color(255, 255, 255));
        cajaCodigodeBarras.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCodigodeBarras.setForeground(new java.awt.Color(102, 102, 102));
        cajaCodigodeBarras.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCodigodeBarras.setBorder(null);
        jPanel1.add(cajaCodigodeBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 210, 30));

        botonBuscarCodigoBarras.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscarCodigoBarras.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonBuscarCodigoBarras.setForeground(new java.awt.Color(102, 102, 102));
        botonBuscarCodigoBarras.setText("Buscar");
        botonBuscarCodigoBarras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarCodigoBarras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBuscarCodigoBarras.setFocusPainted(false);
        botonBuscarCodigoBarras.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonBuscarCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 70, 30));

        botonCrear.setBackground(new java.awt.Color(255, 255, 255));
        botonCrear.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCrear.setForeground(new java.awt.Color(102, 102, 102));
        botonCrear.setText("Crear");
        botonCrear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCrear.setFocusPainted(false);
        botonCrear.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        botonEditar.setBackground(new java.awt.Color(255, 255, 255));
        botonEditar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(102, 102, 102));
        botonEditar.setText("Editar");
        botonEditar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEditar.setFocusPainted(false);
        botonEditar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, -1, -1));

        botonEliminar.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(102, 102, 102));
        botonEliminar.setText("Eliminar");
        botonEliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminar.setFocusPainted(false);
        botonEliminar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nombre :");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 110, 30));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cantidad Stock :");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Precio :");
        jLabel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 100, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Descripción :");
        jLabel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Proveedor :");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 140, 30));

        cajaBuscarPorCodigoBarras.setBackground(new java.awt.Color(255, 255, 255));
        cajaBuscarPorCodigoBarras.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaBuscarPorCodigoBarras.setForeground(new java.awt.Color(204, 204, 204));
        cajaBuscarPorCodigoBarras.setText("Codigo de barras");
        cajaBuscarPorCodigoBarras.setBorder(null);
        cajaBuscarPorCodigoBarras.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaBuscarPorCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 240, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha Vencimiento :");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 140, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Laboratorio :");
        jLabel10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCancelar.setForeground(new java.awt.Color(102, 102, 102));
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelar.setFocusPainted(false);
        botonCancelar.setPreferredSize(new java.awt.Dimension(76, 32));
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        dateChooserFechaVencimiento.setBackground(new java.awt.Color(255, 255, 255));
        dateChooserFechaVencimiento.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(dateChooserFechaVencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 120, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        TextAreaDescripcion.setColumns(20);
        TextAreaDescripcion.setRows(5);
        jScrollPane1.setViewportView(TextAreaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 260, 100));

        comboLaboratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboLaboratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 210, -1));

        comboProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 210, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Codigo Barra :");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 150, 30));

        cajaPrecio.setBackground(new java.awt.Color(255, 255, 255));
        cajaPrecio.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaPrecio.setForeground(new java.awt.Color(102, 102, 102));
        cajaPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaPrecio.setBorder(null);
        jPanel1.add(cajaPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 260, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/codigoBarras.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 30));

        botonLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        botonLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/borrar.png"))); // NOI18N
        botonLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiar.setOpaque(true);
        jPanel1.add(botonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 30, 30));

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 470, 50));

        labelimagenUpLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/cargar-upload.png"))); // NOI18N
        labelimagenUpLoad.setText("jLabel13");
        jPanel1.add(labelimagenUpLoad, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 30, 30));

        labelTextoCargar.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelTextoCargar.setForeground(new java.awt.Color(51, 51, 51));
        labelTextoCargar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTextoCargar.setText("Cargar Imagen...");
        jPanel1.add(labelTextoCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 100, 20));

        labelimagenNombreArchivo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelimagenNombreArchivo.setForeground(new java.awt.Color(102, 102, 102));
        labelimagenNombreArchivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelimagenNombreArchivo.setText("Opcional...");
        jPanel1.add(labelimagenNombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 130, -1));

        labelEliminarImagen.setBackground(new java.awt.Color(255, 255, 255));
        labelEliminarImagen.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelEliminarImagen.setForeground(new java.awt.Color(153, 153, 153));
        labelEliminarImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEliminarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/borrar15x15.png"))); // NOI18N
        jPanel1.add(labelEliminarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 20, -1));

        panelimagen.setOpaque(false);

        javax.swing.GroupLayout panelimagenLayout = new javax.swing.GroupLayout(panelimagen);
        panelimagen.setLayout(panelimagenLayout);
        panelimagenLayout.setHorizontalGroup(
            panelimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelimagenLayout.setVerticalGroup(
            panelimagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(panelimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 100, 100));

        labelNoHayImagen.setBackground(new java.awt.Color(255, 255, 255));
        labelNoHayImagen.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelNoHayImagen.setForeground(new java.awt.Color(102, 102, 102));
        labelNoHayImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNoHayImagen.setText("Imagen");
        labelNoHayImagen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelNoHayImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 20, 100, 100));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/ingresarRegistros.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarProducto dialog = new GestionarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea TextAreaDescripcion;
    public javax.swing.JButton botonBuscarCodigoBarras;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonCrear;
    public javax.swing.JButton botonEditar;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JLabel botonLimpiar;
    public javax.swing.JTextField cajaBuscarPorCodigoBarras;
    public javax.swing.JTextField cajaCantidadStock;
    public javax.swing.JTextField cajaCodigodeBarras;
    public javax.swing.JTextField cajaNombre;
    public javax.swing.JTextField cajaPrecio;
    public javax.swing.JComboBox<String> comboLaboratorio;
    public javax.swing.JComboBox<String> comboProveedor;
    public com.toedter.calendar.JDateChooser dateChooserFechaVencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelEliminarImagen;
    public javax.swing.JLabel labelNoHayImagen;
    public javax.swing.JLabel labelTextoCargar;
    public javax.swing.JLabel labelimagenNombreArchivo;
    public javax.swing.JLabel labelimagenUpLoad;
    public javax.swing.JPanel panelimagen;
    // End of variables declaration//GEN-END:variables
}
