/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class GestionarFacturas extends javax.swing.JDialog {

    /**
     * Creates new form GestionarFacturas
     */
    public GestionarFacturas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDesplegableMouse = new javax.swing.JPopupMenu();
        eliminarDetalleFactura = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleFactura = new javax.swing.JTable();
        botonAnularFactura = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonEditaroCambiar = new javax.swing.JButton();
        labelEstadoFactura = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        labelConsecutivo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cajaConsecutivoFactura = new javax.swing.JTextField();
        labelSigno5 = new javax.swing.JTextField();
        labelSigno6 = new javax.swing.JTextField();
        cajaIngresarDescuento1 = new javax.swing.JTextField();
        cajaIngresarIVA1 = new javax.swing.JTextField();
        labelDescuento1 = new javax.swing.JLabel();
        labelingresarIVA1 = new javax.swing.JLabel();
        cajaCantidadDetalle1 = new javax.swing.JTextField();
        labelAgregarproducto = new javax.swing.JLabel();
        labelNotas = new javax.swing.JLabel();
        botonBorrar1 = new javax.swing.JLabel();
        cajaTotal = new javax.swing.JTextField();
        cajaIvaTotal = new javax.swing.JTextField();
        cajaSubTotal = new javax.swing.JTextField();
        cajaNombreCliente = new javax.swing.JTextField();
        cajaCedulaCliente = new javax.swing.JTextField();
        cajaCodigoBarras1 = new javax.swing.JTextField();
        labelTotal = new javax.swing.JLabel();
        labelIvaToTal = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelCedula = new javax.swing.JLabel();
        labelCantidad2 = new javax.swing.JLabel();
        labelSigno9 = new javax.swing.JTextField();
        labelSigno8 = new javax.swing.JTextField();
        labelSigno7 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tANotas = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        eliminarDetalleFactura.setBackground(new java.awt.Color(255, 255, 255));
        eliminarDetalleFactura.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        eliminarDetalleFactura.setForeground(new java.awt.Color(0, 0, 0));
        eliminarDetalleFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/basura.png"))); // NOI18N
        eliminarDetalleFactura.setText("Eliminar Detalle");
        eliminarDetalleFactura.setBorder(null);
        menuDesplegableMouse.add(eliminarDetalleFactura);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion Facturas");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 440, 40));

        tablaDetalleFactura.setBackground(new java.awt.Color(255, 255, 255));
        tablaDetalleFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaDetalleFactura.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        tablaDetalleFactura.setForeground(new java.awt.Color(0, 0, 0));
        tablaDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalleFactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 760, 140));

        botonAnularFactura.setBackground(new java.awt.Color(255, 255, 255));
        botonAnularFactura.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        botonAnularFactura.setText("Anular ");
        botonAnularFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAnularFactura.setFocusPainted(false);
        jPanel1.add(botonAnularFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 90, 30));

        botonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelar.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setFocusPainted(false);
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, 30));

        botonEditaroCambiar.setBackground(new java.awt.Color(255, 255, 255));
        botonEditaroCambiar.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        botonEditaroCambiar.setText("Devolución/Cambio");
        botonEditaroCambiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEditaroCambiar.setFocusPainted(false);
        jPanel1.add(botonEditaroCambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 130, 30));

        labelEstadoFactura.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelEstadoFactura.setForeground(new java.awt.Color(0, 0, 204));
        labelEstadoFactura.setText("Sin seleccionar");
        jPanel1.add(labelEstadoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 210, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Estado de la Factura :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        botonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscar.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscar.setFocusPainted(false);
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 90, 30));

        labelConsecutivo.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelConsecutivo.setForeground(new java.awt.Color(153, 0, 0));
        labelConsecutivo.setText("Ninguna");
        jPanel1.add(labelConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Factura seleccionada :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("<html>Cliente tiene solo (5) dias habiles despues de realizada la compra para anular factura.</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 350, 30));

        cajaConsecutivoFactura.setBackground(new java.awt.Color(255, 255, 255));
        cajaConsecutivoFactura.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaConsecutivoFactura.setForeground(new java.awt.Color(204, 204, 204));
        cajaConsecutivoFactura.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaConsecutivoFactura.setText("Consecutivo factura");
        cajaConsecutivoFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaConsecutivoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 30));

        labelSigno5.setEditable(false);
        labelSigno5.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno5.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelSigno5.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno5.setText("%");
        labelSigno5.setBorder(null);
        labelSigno5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 30, 20));

        labelSigno6.setEditable(false);
        labelSigno6.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno6.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        labelSigno6.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno6.setText("%");
        labelSigno6.setBorder(null);
        labelSigno6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 20, 20));

        cajaIngresarDescuento1.setBackground(new java.awt.Color(255, 255, 255));
        cajaIngresarDescuento1.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaIngresarDescuento1.setForeground(new java.awt.Color(51, 51, 51));
        cajaIngresarDescuento1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaIngresarDescuento1.setText("0");
        cajaIngresarDescuento1.setBorder(null);
        cajaIngresarDescuento1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaIngresarDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 40, 20));

        cajaIngresarIVA1.setBackground(new java.awt.Color(255, 255, 255));
        cajaIngresarIVA1.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        cajaIngresarIVA1.setForeground(new java.awt.Color(51, 51, 51));
        cajaIngresarIVA1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaIngresarIVA1.setText("4");
        cajaIngresarIVA1.setBorder(null);
        cajaIngresarIVA1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaIngresarIVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 30, 20));

        labelDescuento1.setBackground(new java.awt.Color(255, 255, 255));
        labelDescuento1.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelDescuento1.setForeground(new java.awt.Color(51, 51, 51));
        labelDescuento1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuento1.setText("Descuento :");
        labelDescuento1.setToolTipText("");
        labelDescuento1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelDescuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 100, 20));

        labelingresarIVA1.setBackground(new java.awt.Color(255, 255, 255));
        labelingresarIVA1.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelingresarIVA1.setForeground(new java.awt.Color(51, 51, 51));
        labelingresarIVA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelingresarIVA1.setText("Iva :");
        labelingresarIVA1.setToolTipText("");
        labelingresarIVA1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelingresarIVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 50, 20));

        cajaCantidadDetalle1.setBackground(new java.awt.Color(255, 255, 255));
        cajaCantidadDetalle1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCantidadDetalle1.setForeground(new java.awt.Color(51, 51, 51));
        cajaCantidadDetalle1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCantidadDetalle1.setText("1");
        cajaCantidadDetalle1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCantidadDetalle1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCantidadDetalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 50, 20));

        labelAgregarproducto.setBackground(new java.awt.Color(255, 255, 255));
        labelAgregarproducto.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelAgregarproducto.setForeground(new java.awt.Color(51, 51, 51));
        labelAgregarproducto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelAgregarproducto.setText("Agrega cambio :");
        labelAgregarproducto.setToolTipText("");
        labelAgregarproducto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelAgregarproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 120, 30));

        labelNotas.setBackground(new java.awt.Color(255, 255, 255));
        labelNotas.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelNotas.setForeground(new java.awt.Color(51, 51, 51));
        labelNotas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNotas.setText("Notas :");
        labelNotas.setToolTipText("");
        labelNotas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 120, 20));

        botonBorrar1.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrar1.setForeground(new java.awt.Color(204, 204, 204));
        botonBorrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/borrar.png"))); // NOI18N
        botonBorrar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botonBorrar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar1.setOpaque(true);
        jPanel1.add(botonBorrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, 30, 30));

        cajaTotal.setEditable(false);
        cajaTotal.setBackground(new java.awt.Color(255, 255, 255));
        cajaTotal.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTotal.setText("Sub-Total");
        cajaTotal.setBorder(null);
        jPanel1.add(cajaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 200, 30));

        cajaIvaTotal.setEditable(false);
        cajaIvaTotal.setBackground(new java.awt.Color(255, 255, 255));
        cajaIvaTotal.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaIvaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaIvaTotal.setText("Iva Total");
        cajaIvaTotal.setBorder(null);
        jPanel1.add(cajaIvaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 200, 30));

        cajaSubTotal.setEditable(false);
        cajaSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        cajaSubTotal.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaSubTotal.setText("Sub-Total");
        cajaSubTotal.setBorder(null);
        jPanel1.add(cajaSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 200, 30));

        cajaNombreCliente.setEditable(false);
        cajaNombreCliente.setBackground(new java.awt.Color(255, 255, 255));
        cajaNombreCliente.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaNombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaNombreCliente.setText("Nombre Cliente");
        cajaNombreCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 220, 30));

        cajaCedulaCliente.setEditable(false);
        cajaCedulaCliente.setBackground(new java.awt.Color(255, 255, 255));
        cajaCedulaCliente.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaCedulaCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCedulaCliente.setText("Cedula Cliente");
        cajaCedulaCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(cajaCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 220, 30));

        cajaCodigoBarras1.setBackground(new java.awt.Color(255, 255, 255));
        cajaCodigoBarras1.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCodigoBarras1.setForeground(new java.awt.Color(204, 204, 204));
        cajaCodigoBarras1.setText("Codigo de barras");
        cajaCodigoBarras1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCodigoBarras1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCodigoBarras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 240, 30));

        labelTotal.setBackground(new java.awt.Color(255, 255, 255));
        labelTotal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(51, 51, 51));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText("Total:");
        labelTotal.setToolTipText("");
        labelTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 80, 30));

        labelIvaToTal.setBackground(new java.awt.Color(255, 255, 255));
        labelIvaToTal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelIvaToTal.setForeground(new java.awt.Color(51, 51, 51));
        labelIvaToTal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelIvaToTal.setText("Iva Total:");
        labelIvaToTal.setToolTipText("");
        labelIvaToTal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelIvaToTal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 80, 30));

        labelSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        labelSubtotal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        labelSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtotal.setText("Sub-Total:");
        labelSubtotal.setToolTipText("");
        labelSubtotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 80, 30));

        labelCliente.setBackground(new java.awt.Color(255, 255, 255));
        labelCliente.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCliente.setText("Cliente :");
        labelCliente.setToolTipText("");
        labelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 60, 30));

        labelCedula.setBackground(new java.awt.Color(255, 255, 255));
        labelCedula.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(51, 51, 51));
        labelCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCedula.setText("Cédula :");
        labelCedula.setToolTipText("");
        labelCedula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        labelCantidad2.setBackground(new java.awt.Color(255, 255, 255));
        labelCantidad2.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCantidad2.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidad2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidad2.setText("Cantidad :");
        labelCantidad2.setToolTipText("");
        labelCantidad2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCantidad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 80, 20));

        labelSigno9.setEditable(false);
        labelSigno9.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno9.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        labelSigno9.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno9.setText("%");
        labelSigno9.setBorder(null);
        labelSigno9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 20, 30));

        labelSigno8.setEditable(false);
        labelSigno8.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno8.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        labelSigno8.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno8.setText("%");
        labelSigno8.setBorder(null);
        labelSigno8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno8, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 20, 30));

        labelSigno7.setEditable(false);
        labelSigno7.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno7.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        labelSigno7.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno7.setText("%");
        labelSigno7.setBorder(null);
        labelSigno7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 20, 30));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tANotas.setBackground(new java.awt.Color(255, 255, 255));
        tANotas.setColumns(20);
        tANotas.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        tANotas.setForeground(new java.awt.Color(51, 51, 51));
        tANotas.setRows(5);
        tANotas.setText("*Fecha Anulación: Año/Mes/Dia (En caso de Anulación).\n*Motivo de Anulación: (En caso de Anulación).\n\n*Fecha Cambio: Año/Mes/Dia (En caso de Cambio).\n*Motivo del cambio:(En caso de Cambio).");
        tANotas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(tANotas);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 370, 90));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/facturaFarmacia.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GestionarFacturas dialog = new GestionarFacturas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton botonAnularFactura;
    public javax.swing.JLabel botonBorrar1;
    public javax.swing.JButton botonBuscar;
    public javax.swing.JButton botonCancelar;
    public javax.swing.JButton botonEditaroCambiar;
    public javax.swing.JTextField cajaCantidadDetalle1;
    public javax.swing.JTextField cajaCedulaCliente;
    public javax.swing.JTextField cajaCodigoBarras1;
    public javax.swing.JTextField cajaConsecutivoFactura;
    public javax.swing.JTextField cajaIngresarDescuento1;
    public javax.swing.JTextField cajaIngresarIVA1;
    public javax.swing.JTextField cajaIvaTotal;
    public javax.swing.JTextField cajaNombreCliente;
    public javax.swing.JTextField cajaSubTotal;
    public javax.swing.JTextField cajaTotal;
    public javax.swing.JMenuItem eliminarDetalleFactura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelAgregarproducto;
    public javax.swing.JLabel labelCantidad2;
    public javax.swing.JLabel labelCedula;
    public javax.swing.JLabel labelCliente;
    public javax.swing.JLabel labelConsecutivo;
    public javax.swing.JLabel labelDescuento1;
    public javax.swing.JLabel labelEstadoFactura;
    public javax.swing.JLabel labelIvaToTal;
    public javax.swing.JLabel labelNotas;
    public javax.swing.JTextField labelSigno5;
    public javax.swing.JTextField labelSigno6;
    public javax.swing.JTextField labelSigno7;
    public javax.swing.JTextField labelSigno8;
    public javax.swing.JTextField labelSigno9;
    public javax.swing.JLabel labelSubtotal;
    public javax.swing.JLabel labelTotal;
    public javax.swing.JLabel labelingresarIVA1;
    public javax.swing.JPopupMenu menuDesplegableMouse;
    public javax.swing.JTextArea tANotas;
    public javax.swing.JTable tablaDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
