/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author HP
 */
public class VentanaFacturacion extends javax.swing.JDialog {

    /**
     * Creates new form VentanaFacturacion
     */
    public VentanaFacturacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonGrupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        valorColumna11 = new javax.swing.JLabel();
        valorColumna12 = new javax.swing.JLabel();
        valorColumna13 = new javax.swing.JLabel();
        valorColumna14 = new javax.swing.JLabel();
        valorColumna15 = new javax.swing.JLabel();
        jlabelg = new javax.swing.JLabel();
        labelNit = new javax.swing.JLabel();
        celEmpresa = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        columnaValor = new javax.swing.JLabel();
        columnaImporte = new javax.swing.JLabel();
        columnaDescripcion = new javax.swing.JLabel();
        columnaCantidad = new javax.swing.JLabel();
        numeroFactura = new javax.swing.JLabel();
        facturaVenta = new javax.swing.JLabel();
        departamentoUbicacion = new javax.swing.JLabel();
        telEmpresa = new javax.swing.JLabel();
        NombreEmpresa = new javax.swing.JLabel();
        dirEmpresa = new javax.swing.JLabel();
        nitEmpresa = new javax.swing.JLabel();
        BloqueEncabezado = new javax.swing.JLabel();
        columnaCodigoBarras = new javax.swing.JLabel();
        valorColumna10 = new javax.swing.JLabel();
        valorColumna9 = new javax.swing.JLabel();
        valorColumna8 = new javax.swing.JLabel();
        valorColumna7 = new javax.swing.JLabel();
        valorColumna6 = new javax.swing.JLabel();
        valorColumna5 = new javax.swing.JLabel();
        valorColumna4 = new javax.swing.JLabel();
        valorColumna3 = new javax.swing.JLabel();
        valorColumna2 = new javax.swing.JLabel();
        valorColumna = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        masIVA = new javax.swing.JLabel();
        cajaMontoPagadoCliente = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        valorMasIVA = new javax.swing.JLabel();
        valorTotal = new javax.swing.JLabel();
        bloqueColumnasDetalle = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        valorSubTotal = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        labelOtroMetodo = new javax.swing.JLabel();
        radioOtro = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        radioEfectivo = new javax.swing.JRadioButton();
        radioTarjeta = new javax.swing.JRadioButton();
        montoPagado = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        labelCambioDevolver = new javax.swing.JFormattedTextField();
        botonOk = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        botonPasarMonto = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fechaHora = new javax.swing.JLabel();
        cantidad_Articulos_entregados = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        nombreAtiende = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        valorColumna11.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna11.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna11.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna11.setText("*****");
        jPanel1.add(valorColumna11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 50, -1));

        valorColumna12.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna12.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna12.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna12.setText("*******");
        valorColumna12.setToolTipText("");
        jPanel1.add(valorColumna12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 90, -1));

        valorColumna13.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna13.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna13.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna13.setText("*******");
        jPanel1.add(valorColumna13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 100, -1));

        valorColumna14.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna14.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna14.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna14.setText("******");
        jPanel1.add(valorColumna14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 70, -1));

        valorColumna15.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna15.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna15.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna15.setText("*******");
        jPanel1.add(valorColumna15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 90, -1));

        jlabelg.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jlabelg.setForeground(new java.awt.Color(0, 0, 0));
        jlabelg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlabelg.setText("-");
        jPanel1.add(jlabelg, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 10, -1));

        labelNit.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelNit.setForeground(new java.awt.Color(0, 0, 0));
        labelNit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNit.setText("Nit.");
        jPanel1.add(labelNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 30, -1));

        celEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        celEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        celEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        celEmpresa.setText("3004789612");
        jPanel1.add(celEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 190, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/carrito.gif"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 130, 110));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/carrito de compras.jpg"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 60));

        columnaValor.setBackground(new java.awt.Color(225, 225, 238));
        columnaValor.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        columnaValor.setForeground(new java.awt.Color(0, 0, 0));
        columnaValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnaValor.setText("Valor Unit.");
        columnaValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        columnaValor.setOpaque(true);
        jPanel1.add(columnaValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, 20));

        columnaImporte.setBackground(new java.awt.Color(225, 225, 238));
        columnaImporte.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        columnaImporte.setForeground(new java.awt.Color(0, 0, 0));
        columnaImporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnaImporte.setText("Importe");
        columnaImporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        columnaImporte.setOpaque(true);
        jPanel1.add(columnaImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 90, 20));

        columnaDescripcion.setBackground(new java.awt.Color(225, 225, 238));
        columnaDescripcion.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        columnaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        columnaDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnaDescripcion.setText("Codigo barras");
        columnaDescripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        columnaDescripcion.setOpaque(true);
        jPanel1.add(columnaDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        columnaCantidad.setBackground(new java.awt.Color(225, 225, 238));
        columnaCantidad.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        columnaCantidad.setForeground(new java.awt.Color(0, 0, 0));
        columnaCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnaCantidad.setText("Cant.");
        columnaCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        columnaCantidad.setOpaque(true);
        jPanel1.add(columnaCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 50, 20));

        numeroFactura.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        numeroFactura.setForeground(new java.awt.Color(204, 0, 51));
        numeroFactura.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        numeroFactura.setText("0000000");
        jPanel1.add(numeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 120, -1));

        facturaVenta.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        facturaVenta.setForeground(new java.awt.Color(0, 0, 0));
        facturaVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        facturaVenta.setText("FACTURA VENTA No.");
        jPanel1.add(facturaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 120, -1));

        departamentoUbicacion.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        departamentoUbicacion.setForeground(new java.awt.Color(0, 0, 0));
        departamentoUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        departamentoUbicacion.setText("Soledad-Atlantico");
        jPanel1.add(departamentoUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 400, -1));

        telEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        telEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        telEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        telEmpresa.setText("6053602034");
        jPanel1.add(telEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 200, -1));

        NombreEmpresa.setBackground(new java.awt.Color(225, 225, 238));
        NombreEmpresa.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        NombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa.setText("Empresa Rozón Social");
        NombreEmpresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NombreEmpresa.setOpaque(true);
        jPanel1.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        dirEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        dirEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        dirEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dirEmpresa.setText("Calle 98 # 53-174");
        jPanel1.add(dirEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, -1));

        nitEmpresa.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        nitEmpresa.setForeground(new java.awt.Color(0, 0, 0));
        nitEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nitEmpresa.setText("325801134-7");
        jPanel1.add(nitEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 220, -1));

        BloqueEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        BloqueEncabezado.setOpaque(true);
        jPanel1.add(BloqueEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 160));

        columnaCodigoBarras.setBackground(new java.awt.Color(225, 225, 238));
        columnaCodigoBarras.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        columnaCodigoBarras.setForeground(new java.awt.Color(0, 0, 0));
        columnaCodigoBarras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnaCodigoBarras.setText("Descripción");
        columnaCodigoBarras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        columnaCodigoBarras.setOpaque(true);
        jPanel1.add(columnaCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 100, 20));

        valorColumna10.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna10.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna10.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna10.setText("*******");
        jPanel1.add(valorColumna10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 90, 30));

        valorColumna9.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna9.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna9.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna9.setText("OK");
        jPanel1.add(valorColumna9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, 30));

        valorColumna8.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna8.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna8.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna8.setText("******");
        jPanel1.add(valorColumna8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 70, 30));

        valorColumna7.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna7.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna7.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna7.setText("OK");
        jPanel1.add(valorColumna7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 70, 30));

        valorColumna6.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna6.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna6.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna6.setText("OK");
        jPanel1.add(valorColumna6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 30));

        valorColumna5.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna5.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna5.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna5.setText("*******");
        jPanel1.add(valorColumna5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 100, 30));

        valorColumna4.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna4.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna4.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna4.setText("*******");
        valorColumna4.setToolTipText("");
        jPanel1.add(valorColumna4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        valorColumna3.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna3.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna3.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna3.setText("OK");
        jPanel1.add(valorColumna3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 30));

        valorColumna2.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna2.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna2.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna2.setText("*****");
        jPanel1.add(valorColumna2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 50, 30));

        valorColumna.setBackground(new java.awt.Color(255, 255, 255));
        valorColumna.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorColumna.setForeground(new java.awt.Color(0, 0, 0));
        valorColumna.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorColumna.setText("OK");
        jPanel1.add(valorColumna, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 90, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 50, 60));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 90, 60));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 100, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 70, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 80));

        masIVA.setBackground(new java.awt.Color(225, 225, 238));
        masIVA.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        masIVA.setForeground(new java.awt.Color(0, 0, 0));
        masIVA.setText("Mas IVA");
        masIVA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        masIVA.setOpaque(true);
        jPanel1.add(masIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 100, 20));

        cajaMontoPagadoCliente.setBackground(new java.awt.Color(225, 225, 238));
        cajaMontoPagadoCliente.setBorder(null);
        cajaMontoPagadoCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        cajaMontoPagadoCliente.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        cajaMontoPagadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaMontoPagadoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(cajaMontoPagadoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 100, 20));

        jLabel13.setBackground(new java.awt.Color(225, 225, 238));
        jLabel13.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("$");
        jLabel13.setOpaque(true);
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 20, 20));

        jLabel14.setBackground(new java.awt.Color(225, 225, 238));
        jLabel14.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("$");
        jLabel14.setOpaque(true);
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 20, 20));

        jLabel11.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("$");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 20, 20));

        jLabel12.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("$");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 20, 20));

        valorMasIVA.setBackground(new java.awt.Color(225, 225, 238));
        valorMasIVA.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorMasIVA.setForeground(new java.awt.Color(0, 0, 0));
        valorMasIVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorMasIVA.setText("0");
        valorMasIVA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valorMasIVA.setOpaque(true);
        jPanel1.add(valorMasIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, 20));

        valorTotal.setBackground(new java.awt.Color(225, 225, 238));
        valorTotal.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        valorTotal.setForeground(new java.awt.Color(0, 0, 0));
        valorTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorTotal.setText("0");
        valorTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valorTotal.setOpaque(true);
        jPanel1.add(valorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 20));

        bloqueColumnasDetalle.setBackground(new java.awt.Color(255, 255, 255));
        bloqueColumnasDetalle.setOpaque(true);
        jPanel1.add(bloqueColumnasDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 80));

        total.setBackground(new java.awt.Color(225, 225, 238));
        total.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 0));
        total.setText("Total a pagar");
        total.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        total.setOpaque(true);
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 100, 20));

        jLabel10.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("$");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 20, 20));

        valorSubTotal.setBackground(new java.awt.Color(225, 225, 238));
        valorSubTotal.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        valorSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        valorSubTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorSubTotal.setText("0");
        valorSubTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        valorSubTotal.setOpaque(true);
        jPanel1.add(valorSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, -1));

        subTotal.setBackground(new java.awt.Color(225, 225, 238));
        subTotal.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        subTotal.setForeground(new java.awt.Color(0, 0, 0));
        subTotal.setText("Sub-total");
        subTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        subTotal.setOpaque(true);
        jPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 100, -1));

        labelOtroMetodo.setBackground(new java.awt.Color(225, 225, 238));
        labelOtroMetodo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelOtroMetodo.setForeground(new java.awt.Color(0, 0, 0));
        labelOtroMetodo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOtroMetodo.setText("Otros");
        labelOtroMetodo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelOtroMetodo.setOpaque(true);
        jPanel1.add(labelOtroMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 60, -1));

        radioOtro.setBackground(new java.awt.Color(255, 255, 255));
        radioOtro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(radioOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 20));

        jLabel8.setBackground(new java.awt.Color(225, 225, 238));
        jLabel8.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tarjeta");
        jLabel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, -1));

        jLabel9.setBackground(new java.awt.Color(225, 225, 238));
        jLabel9.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Efectivo");
        jLabel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, -1));

        radioEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        radioEfectivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(radioEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, 20));

        radioTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        radioTarjeta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(radioTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, 20));

        montoPagado.setBackground(new java.awt.Color(225, 225, 238));
        montoPagado.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        montoPagado.setForeground(new java.awt.Color(0, 0, 0));
        montoPagado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        montoPagado.setText("Monto Pagado");
        montoPagado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        montoPagado.setOpaque(true);
        jPanel1.add(montoPagado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 100, 20));

        cambio.setBackground(new java.awt.Color(225, 225, 238));
        cambio.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 0, 0));
        cambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cambio.setText("Cambio");
        cambio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cambio.setOpaque(true);
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 20));

        botonCancelar.setBackground(new java.awt.Color(225, 225, 238));
        botonCancelar.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelar.setFocusPainted(false);
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 60, 20));

        labelCambioDevolver.setBackground(new java.awt.Color(225, 225, 238));
        labelCambioDevolver.setBorder(null);
        labelCambioDevolver.setForeground(new java.awt.Color(204, 0, 51));
        labelCambioDevolver.setText("0");
        labelCambioDevolver.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        jPanel1.add(labelCambioDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 100, 20));

        botonOk.setBackground(new java.awt.Color(0, 102, 102));
        botonOk.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        botonOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/fact.png"))); // NOI18N
        botonOk.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOk.setFocusPainted(false);
        jPanel1.add(botonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 50, 50));

        jLabel24.setBackground(new java.awt.Color(225, 225, 238));
        jLabel24.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 310, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/cash.jpg"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 30, 40));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/otrosMediosPago.png"))); // NOI18N
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 30, 40));

        botonPasarMonto.setBackground(new java.awt.Color(255, 255, 255));
        botonPasarMonto.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        botonPasarMonto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/flechasBidirecionales.png"))); // NOI18N
        botonPasarMonto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPasarMonto.setFocusPainted(false);
        botonPasarMonto.setOpaque(false);
        jPanel1.add(botonPasarMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 30, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/tarjeta.jpg"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 30, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 400, 170));

        fechaHora.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        fechaHora.setForeground(new java.awt.Color(0, 0, 0));
        fechaHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaHora.setText("0000/00/00 00:00:00");
        jPanel1.add(fechaHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 400, 20));

        cantidad_Articulos_entregados.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cantidad_Articulos_entregados.setForeground(new java.awt.Color(0, 0, 0));
        cantidad_Articulos_entregados.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantidad_Articulos_entregados.setText("0");
        jPanel1.add(cantidad_Articulos_entregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 120, 20));

        jLabel26.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Numero de articulos entregados : ");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 280, 20));

        nombreAtiende.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        nombreAtiende.setForeground(new java.awt.Color(0, 0, 0));
        nombreAtiende.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nombreAtiende.setText("Nombre atiende");
        jPanel1.add(nombreAtiende, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 220, 20));

        jLabel22.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Atendido por : ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 180, 20));

        jLabel21.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("DES Company NIT 114. 082.804-4");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 400, 20));

        jLabel20.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Sistema P.O.S  MARVEN - Desarrollado por:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 400, 20));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setOpaque(true);
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 400, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cajaMontoPagadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaMontoPagadoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaMontoPagadoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaFacturacion dialog = new VentanaFacturacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BloqueEncabezado;
    public javax.swing.JLabel NombreEmpresa;
    private javax.swing.JLabel bloqueColumnasDetalle;
    public javax.swing.JButton botonCancelar;
    public javax.swing.ButtonGroup botonGrupo;
    public javax.swing.JButton botonOk;
    public javax.swing.JButton botonPasarMonto;
    public javax.swing.JFormattedTextField cajaMontoPagadoCliente;
    private javax.swing.JLabel cambio;
    public javax.swing.JLabel cantidad_Articulos_entregados;
    public javax.swing.JLabel celEmpresa;
    private javax.swing.JLabel columnaCantidad;
    private javax.swing.JLabel columnaCodigoBarras;
    private javax.swing.JLabel columnaDescripcion;
    private javax.swing.JLabel columnaImporte;
    private javax.swing.JLabel columnaValor;
    public javax.swing.JLabel departamentoUbicacion;
    public javax.swing.JLabel dirEmpresa;
    private javax.swing.JLabel facturaVenta;
    public javax.swing.JLabel fechaHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel jlabelg;
    public javax.swing.JFormattedTextField labelCambioDevolver;
    public javax.swing.JLabel labelNit;
    private javax.swing.JLabel labelOtroMetodo;
    private javax.swing.JLabel masIVA;
    private javax.swing.JLabel montoPagado;
    public javax.swing.JLabel nitEmpresa;
    public javax.swing.JLabel nombreAtiende;
    public javax.swing.JLabel numeroFactura;
    public javax.swing.JRadioButton radioEfectivo;
    public javax.swing.JRadioButton radioOtro;
    public javax.swing.JRadioButton radioTarjeta;
    private javax.swing.JLabel subTotal;
    public javax.swing.JLabel telEmpresa;
    private javax.swing.JLabel total;
    private javax.swing.JLabel valorColumna;
    private javax.swing.JLabel valorColumna10;
    private javax.swing.JLabel valorColumna11;
    private javax.swing.JLabel valorColumna12;
    private javax.swing.JLabel valorColumna13;
    private javax.swing.JLabel valorColumna14;
    private javax.swing.JLabel valorColumna15;
    private javax.swing.JLabel valorColumna2;
    private javax.swing.JLabel valorColumna3;
    private javax.swing.JLabel valorColumna4;
    private javax.swing.JLabel valorColumna5;
    private javax.swing.JLabel valorColumna6;
    private javax.swing.JLabel valorColumna7;
    private javax.swing.JLabel valorColumna8;
    private javax.swing.JLabel valorColumna9;
    public javax.swing.JLabel valorMasIVA;
    public javax.swing.JLabel valorSubTotal;
    public javax.swing.JLabel valorTotal;
    // End of variables declaration//GEN-END:variables
}
