/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setIconImage(getIconImage());
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("vista/Imagenes/LogoMarvenFrame.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelUsuarioActivo = new javax.swing.JLabel();
        labelCargo = new javax.swing.JLabel();
        cajaCliente = new javax.swing.JTextField();
        labelimagenCodigobarras = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JLabel();
        botonOk = new javax.swing.JLabel();
        cajaCodigoBarras = new javax.swing.JTextField();
        labelBloqueIngresar = new javax.swing.JLabel();
        labelImagenProducto = new javax.swing.JLabel();
        labelCantidadenStock = new javax.swing.JLabel();
        botonModificarVenta = new javax.swing.JButton();
        botonFacturar = new javax.swing.JButton();
        botonLimpiarVenta = new javax.swing.JButton();
        labelCliente = new javax.swing.JLabel();
        labelStock = new javax.swing.JLabel();
        botonCancelarMod = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        cajaTotal = new javax.swing.JTextField();
        labelAtiende = new javax.swing.JLabel();
        cajaAtiende = new javax.swing.JTextField();
        labelConfirmaClienteEnDB = new javax.swing.JLabel();
        botonCerrarCaja = new javax.swing.JButton();
        botonModificarDetalle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDetalleFactura = new javax.swing.JTable();
        labelBloqueBotonesParaDetalle = new javax.swing.JLabel();
        labelClienteAMostrar = new javax.swing.JLabel();
        labelClienteNoRegistrado = new javax.swing.JLabel();
        labelMostrarClienteEncontrado = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        cajaCantidadDetalle = new javax.swing.JTextField();
        cajaIngresarDescuento = new javax.swing.JTextField();
        labelDescuento = new javax.swing.JLabel();
        botonEliminarDetalle = new javax.swing.JButton();
        cajaSubtotal = new javax.swing.JTextField();
        labelSubtotal = new javax.swing.JLabel();
        labelingresarIVA = new javax.swing.JLabel();
        cajaIngresarIVA = new javax.swing.JTextField();
        labelSigno1 = new javax.swing.JTextField();
        labelSigno2 = new javax.swing.JTextField();
        label_IvaTotal = new javax.swing.JLabel();
        labelSigno5 = new javax.swing.JTextField();
        caja_IvaTotal = new javax.swing.JTextField();
        cajaCantidadDetalleAModificar = new javax.swing.JTextField();
        labelCantidadAModificar = new javax.swing.JLabel();
        caja_IvaModificar = new javax.swing.JTextField();
        label_IvaModificar = new javax.swing.JLabel();
        labelDescuentoAModificar = new javax.swing.JLabel();
        cajaDescuentoAModificar = new javax.swing.JTextField();
        labelSigno6 = new javax.swing.JTextField();
        labelSigno7 = new javax.swing.JTextField();
        labelBloqueModificar = new javax.swing.JLabel();
        labelproductoSelecionadoTabla = new javax.swing.JLabel();
        labelNombreProductoSelecionadoTabla = new javax.swing.JLabel();
        labelSeleccioneItem = new javax.swing.JLabel();
        botonActualizarVenta = new javax.swing.JButton();
        labelBloqueTabla = new javax.swing.JLabel();
        labelSigno3 = new javax.swing.JTextField();
        labelSigno4 = new javax.swing.JTextField();
        panelimagenes = new javax.swing.JPanel();
        labelReloj = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItemCerrarSesion = new javax.swing.JMenuItem();
        menuItemSalir = new javax.swing.JMenuItem();
        menuGestionar = new javax.swing.JMenu();
        itemGestionarMedicamentos = new javax.swing.JMenuItem();
        itemGestionarProveedores = new javax.swing.JMenuItem();
        itemGestionarLaboratorios = new javax.swing.JMenuItem();
        itemGestionarClientes = new javax.swing.JMenuItem();
        MenuRealizar = new javax.swing.JMenu();
        itemRealizarVentas = new javax.swing.JMenuItem();
        itemRealizarDevolucionesOcambio = new javax.swing.JMenuItem();
        MenuConsultar = new javax.swing.JMenu();
        itemConsultarMedicamentos = new javax.swing.JMenuItem();
        itemConsultarProveedores = new javax.swing.JMenuItem();
        itemConsultarLaboratorios = new javax.swing.JMenuItem();
        itemConsultarClientes = new javax.swing.JMenuItem();
        itemConsultarVentas = new javax.swing.JMenuItem();
        itemConsultarFactura = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        itemReporteInventarioMedicamentos = new javax.swing.JMenuItem();
        itemReporteMedicamentosVencer = new javax.swing.JMenuItem();
        itemReporteDevolucionesCambios = new javax.swing.JMenuItem();
        itemReporteGeneralVentas = new javax.swing.JMenuItem();
        menuAdministrador = new javax.swing.JMenu();
        itemGestionarFacturas = new javax.swing.JMenuItem();
        conf_infoEmpresaClienteDelSoftware = new javax.swing.JMenuItem();
        itemConfIVADes = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        subMenuCrearUsuario = new javax.swing.JMenu();
        itemCrearUsuarios = new javax.swing.JMenuItem();
        itemBuscarUsuarios = new javax.swing.JMenuItem();
        itemEditarUsuarios = new javax.swing.JMenuItem();
        itemEliminarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmacia");
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUsuarioActivo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelUsuarioActivo.setForeground(new java.awt.Color(0, 0, 51));
        labelUsuarioActivo.setText("jLabel2");
        jPanel1.add(labelUsuarioActivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 230, 20));

        labelCargo.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelCargo.setForeground(new java.awt.Color(0, 0, 51));
        labelCargo.setText("jLabel2");
        jPanel1.add(labelCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, -1));

        cajaCliente.setBackground(new java.awt.Color(255, 255, 255));
        cajaCliente.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCliente.setForeground(new java.awt.Color(204, 204, 204));
        cajaCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCliente.setText("Cedula Cliente");
        cajaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 170, 30));

        labelimagenCodigobarras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/codigoBarras.png"))); // NOI18N
        jPanel1.add(labelimagenCodigobarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 100, 30));

        botonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrar.setForeground(new java.awt.Color(204, 204, 204));
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/borrar.png"))); // NOI18N
        botonBorrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar.setOpaque(true);
        jPanel1.add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 30, 30));

        botonOk.setBackground(new java.awt.Color(250, 250, 250));
        botonOk.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonOk.setForeground(new java.awt.Color(51, 51, 51));
        botonOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonOk.setText("OK");
        botonOk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        botonOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonOk.setOpaque(true);
        jPanel1.add(botonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 60, 60, 30));

        cajaCodigoBarras.setBackground(new java.awt.Color(255, 255, 255));
        cajaCodigoBarras.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCodigoBarras.setForeground(new java.awt.Color(204, 204, 204));
        cajaCodigoBarras.setText("Codigo de barras");
        cajaCodigoBarras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCodigoBarras.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCodigoBarras, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 240, 30));

        labelBloqueIngresar.setBackground(new java.awt.Color(204, 204, 204));
        labelBloqueIngresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelBloqueIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 470, 50));

        labelImagenProducto.setBackground(new java.awt.Color(255, 255, 255));
        labelImagenProducto.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        labelImagenProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImagenProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/es.gif"))); // NOI18N
        labelImagenProducto.setText("Imagen");
        labelImagenProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        labelImagenProducto.setOpaque(true);
        jPanel1.add(labelImagenProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 300));

        labelCantidadenStock.setBackground(new java.awt.Color(255, 255, 255));
        labelCantidadenStock.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCantidadenStock.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadenStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidadenStock.setText("X");
        labelCantidadenStock.setToolTipText("");
        labelCantidadenStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCantidadenStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 60, 30));

        botonModificarVenta.setBackground(new java.awt.Color(255, 255, 255));
        botonModificarVenta.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonModificarVenta.setForeground(new java.awt.Color(51, 51, 51));
        botonModificarVenta.setText("Modificar Venta");
        botonModificarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonModificarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarVenta.setFocusable(false);
        jPanel1.add(botonModificarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, 130, 40));

        botonFacturar.setBackground(new java.awt.Color(255, 255, 255));
        botonFacturar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonFacturar.setForeground(new java.awt.Color(51, 51, 51));
        botonFacturar.setText("Facturar");
        botonFacturar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonFacturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonFacturar.setFocusable(false);
        jPanel1.add(botonFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 130, 40));

        botonLimpiarVenta.setBackground(new java.awt.Color(255, 255, 255));
        botonLimpiarVenta.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonLimpiarVenta.setForeground(new java.awt.Color(51, 51, 51));
        botonLimpiarVenta.setText("Limpiar Venta");
        botonLimpiarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonLimpiarVenta.setFocusable(false);
        jPanel1.add(botonLimpiarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 130, 40));

        labelCliente.setBackground(new java.awt.Color(255, 255, 255));
        labelCliente.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCliente.setForeground(new java.awt.Color(51, 51, 51));
        labelCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCliente.setText("Cliente :");
        labelCliente.setToolTipText("");
        labelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 90, 90, 30));

        labelStock.setBackground(new java.awt.Color(255, 255, 255));
        labelStock.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelStock.setForeground(new java.awt.Color(51, 51, 51));
        labelStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStock.setText("Stock :");
        labelStock.setToolTipText("");
        labelStock.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 60, 30));

        botonCancelarMod.setBackground(new java.awt.Color(255, 255, 255));
        botonCancelarMod.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCancelarMod.setForeground(new java.awt.Color(51, 51, 51));
        botonCancelarMod.setText("Cancelar");
        botonCancelarMod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCancelarMod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCancelarMod.setFocusable(false);
        jPanel1.add(botonCancelarMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 600, 90, 30));

        labelTotal.setBackground(new java.awt.Color(255, 255, 255));
        labelTotal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(51, 51, 51));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText("TOTAL :");
        labelTotal.setToolTipText("");
        labelTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, 110, 30));

        cajaTotal.setBackground(new java.awt.Color(255, 255, 255));
        cajaTotal.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaTotal.setForeground(new java.awt.Color(51, 51, 51));
        cajaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaTotal.setBorder(null);
        cajaTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 600, 260, 30));

        labelAtiende.setBackground(new java.awt.Color(255, 255, 255));
        labelAtiende.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelAtiende.setForeground(new java.awt.Color(51, 51, 51));
        labelAtiende.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAtiende.setText("Atiende :");
        labelAtiende.setToolTipText("");
        labelAtiende.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelAtiende, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 90, 30));

        cajaAtiende.setBackground(new java.awt.Color(255, 255, 255));
        cajaAtiende.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaAtiende.setForeground(new java.awt.Color(51, 51, 51));
        cajaAtiende.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaAtiende.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaAtiende.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaAtiende, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 50, 170, 30));

        labelConfirmaClienteEnDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/correcto.png"))); // NOI18N
        jPanel1.add(labelConfirmaClienteEnDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 90, 30, 30));

        botonCerrarCaja.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrarCaja.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonCerrarCaja.setForeground(new java.awt.Color(51, 51, 51));
        botonCerrarCaja.setText("Cerrar Caja");
        botonCerrarCaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonCerrarCaja.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarCaja.setFocusable(false);
        jPanel1.add(botonCerrarCaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 130, 40));

        botonModificarDetalle.setBackground(new java.awt.Color(255, 255, 255));
        botonModificarDetalle.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonModificarDetalle.setForeground(new java.awt.Color(51, 51, 51));
        botonModificarDetalle.setText("Modificar");
        botonModificarDetalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonModificarDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModificarDetalle.setFocusable(false);
        jPanel1.add(botonModificarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 90, 30));

        tablaDetalleFactura.setBackground(new java.awt.Color(255, 255, 255));
        tablaDetalleFactura.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        tablaDetalleFactura.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        tablaDetalleFactura.setForeground(new java.awt.Color(51, 51, 51));
        tablaDetalleFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDetalleFactura);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 211, 890, 320));

        labelBloqueBotonesParaDetalle.setBackground(new java.awt.Color(255, 255, 255));
        labelBloqueBotonesParaDetalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelBloqueBotonesParaDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 190, 270));

        labelClienteAMostrar.setBackground(new java.awt.Color(255, 255, 255));
        labelClienteAMostrar.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelClienteAMostrar.setForeground(new java.awt.Color(51, 102, 0));
        labelClienteAMostrar.setText("<html><body>Cliente <br>Señor@  :</html></body>");
        jPanel1.add(labelClienteAMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 60, 40));

        labelClienteNoRegistrado.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelClienteNoRegistrado.setForeground(new java.awt.Color(204, 0, 0));
        labelClienteNoRegistrado.setText("<html><body>*Cliente No registra en nuestra base de datos presionar aqui para registrar</html></body>");
        labelClienteNoRegistrado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(labelClienteNoRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 120, 240, 40));

        labelMostrarClienteEncontrado.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelMostrarClienteEncontrado.setForeground(new java.awt.Color(51, 102, 0));
        jPanel1.add(labelMostrarClienteEncontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 290, 40));

        labelCantidad.setBackground(new java.awt.Color(255, 255, 255));
        labelCantidad.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCantidad.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidad.setText("Cantidad :");
        labelCantidad.setToolTipText("");
        labelCantidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 110, 30));

        cajaCantidadDetalle.setBackground(new java.awt.Color(255, 255, 255));
        cajaCantidadDetalle.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCantidadDetalle.setForeground(new java.awt.Color(51, 51, 51));
        cajaCantidadDetalle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCantidadDetalle.setText("1");
        cajaCantidadDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCantidadDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCantidadDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 70, 30));

        cajaIngresarDescuento.setBackground(new java.awt.Color(255, 255, 255));
        cajaIngresarDescuento.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        cajaIngresarDescuento.setForeground(new java.awt.Color(51, 51, 51));
        cajaIngresarDescuento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaIngresarDescuento.setText("0");
        cajaIngresarDescuento.setBorder(null);
        cajaIngresarDescuento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaIngresarDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 180, 40, 20));

        labelDescuento.setBackground(new java.awt.Color(255, 255, 255));
        labelDescuento.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelDescuento.setForeground(new java.awt.Color(51, 51, 51));
        labelDescuento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuento.setText("Descuento :");
        labelDescuento.setToolTipText("");
        labelDescuento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, 100, 20));

        botonEliminarDetalle.setBackground(new java.awt.Color(255, 255, 255));
        botonEliminarDetalle.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        botonEliminarDetalle.setForeground(new java.awt.Color(51, 51, 51));
        botonEliminarDetalle.setText("Eliminar");
        botonEliminarDetalle.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminarDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEliminarDetalle.setFocusable(false);
        jPanel1.add(botonEliminarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 600, 90, 30));

        cajaSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        cajaSubtotal.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        cajaSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaSubtotal.setBorder(null);
        cajaSubtotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 260, 30));

        labelSubtotal.setBackground(new java.awt.Color(255, 255, 255));
        labelSubtotal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelSubtotal.setForeground(new java.awt.Color(51, 51, 51));
        labelSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubtotal.setText("Sub-Total");
        labelSubtotal.setToolTipText("");
        labelSubtotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 110, 30));

        labelingresarIVA.setBackground(new java.awt.Color(255, 255, 255));
        labelingresarIVA.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelingresarIVA.setForeground(new java.awt.Color(51, 51, 51));
        labelingresarIVA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelingresarIVA.setText("Iva :");
        labelingresarIVA.setToolTipText("");
        labelingresarIVA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelingresarIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 160, 50, 20));

        cajaIngresarIVA.setBackground(new java.awt.Color(255, 255, 255));
        cajaIngresarIVA.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        cajaIngresarIVA.setForeground(new java.awt.Color(51, 51, 51));
        cajaIngresarIVA.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaIngresarIVA.setText("4");
        cajaIngresarIVA.setBorder(null);
        cajaIngresarIVA.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaIngresarIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 30, 20));

        labelSigno1.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno1.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        labelSigno1.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno1.setText("$");
        labelSigno1.setBorder(null);
        labelSigno1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 40, 30));

        labelSigno2.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno2.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        labelSigno2.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno2.setText("$");
        labelSigno2.setBorder(null);
        labelSigno2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 40, 30));

        label_IvaTotal.setBackground(new java.awt.Color(255, 255, 255));
        label_IvaTotal.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        label_IvaTotal.setForeground(new java.awt.Color(51, 51, 51));
        label_IvaTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_IvaTotal.setText("Tatal IVA :");
        label_IvaTotal.setToolTipText("");
        label_IvaTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(label_IvaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 110, 30));

        labelSigno5.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno5.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        labelSigno5.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno5.setText("$");
        labelSigno5.setBorder(null);
        labelSigno5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 560, 40, 30));

        caja_IvaTotal.setBackground(new java.awt.Color(255, 255, 255));
        caja_IvaTotal.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        caja_IvaTotal.setForeground(new java.awt.Color(51, 51, 51));
        caja_IvaTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caja_IvaTotal.setBorder(null);
        caja_IvaTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(caja_IvaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 560, 260, 30));

        cajaCantidadDetalleAModificar.setBackground(new java.awt.Color(255, 255, 255));
        cajaCantidadDetalleAModificar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaCantidadDetalleAModificar.setForeground(new java.awt.Color(51, 51, 51));
        cajaCantidadDetalleAModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaCantidadDetalleAModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        cajaCantidadDetalleAModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaCantidadDetalleAModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 60, 30));

        labelCantidadAModificar.setBackground(new java.awt.Color(255, 255, 255));
        labelCantidadAModificar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelCantidadAModificar.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadAModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCantidadAModificar.setText("Cantidad :");
        labelCantidadAModificar.setToolTipText("");
        labelCantidadAModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelCantidadAModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 90, 30));

        caja_IvaModificar.setBackground(new java.awt.Color(255, 255, 255));
        caja_IvaModificar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        caja_IvaModificar.setForeground(new java.awt.Color(51, 51, 51));
        caja_IvaModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caja_IvaModificar.setBorder(null);
        caja_IvaModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(caja_IvaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 60, 30));

        label_IvaModificar.setBackground(new java.awt.Color(255, 255, 255));
        label_IvaModificar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        label_IvaModificar.setForeground(new java.awt.Color(51, 51, 51));
        label_IvaModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_IvaModificar.setText("Iva  :");
        label_IvaModificar.setToolTipText("");
        label_IvaModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(label_IvaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 550, 90, 30));

        labelDescuentoAModificar.setBackground(new java.awt.Color(255, 255, 255));
        labelDescuentoAModificar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelDescuentoAModificar.setForeground(new java.awt.Color(51, 51, 51));
        labelDescuentoAModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescuentoAModificar.setText("Descuento :");
        labelDescuentoAModificar.setToolTipText("");
        labelDescuentoAModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelDescuentoAModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 90, 30));

        cajaDescuentoAModificar.setBackground(new java.awt.Color(255, 255, 255));
        cajaDescuentoAModificar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        cajaDescuentoAModificar.setForeground(new java.awt.Color(51, 51, 51));
        cajaDescuentoAModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cajaDescuentoAModificar.setBorder(null);
        cajaDescuentoAModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(cajaDescuentoAModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 550, 60, 30));

        labelSigno6.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno6.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        labelSigno6.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno6.setText("%");
        labelSigno6.setBorder(null);
        labelSigno6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 30, 30));

        labelSigno7.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno7.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        labelSigno7.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno7.setText("%");
        labelSigno7.setBorder(null);
        labelSigno7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 550, 30, 30));

        labelBloqueModificar.setBackground(new java.awt.Color(255, 255, 255));
        labelBloqueModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelBloqueModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 536, 630, 50));

        labelproductoSelecionadoTabla.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        labelproductoSelecionadoTabla.setForeground(new java.awt.Color(51, 102, 0));
        labelproductoSelecionadoTabla.setText("<html><body>Producto<br>Seleccionado  :</html></body>");
        jPanel1.add(labelproductoSelecionadoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 90, 30));

        labelNombreProductoSelecionadoTabla.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        labelNombreProductoSelecionadoTabla.setForeground(new java.awt.Color(51, 102, 0));
        labelNombreProductoSelecionadoTabla.setText("<html><body><br></html></body>");
        jPanel1.add(labelNombreProductoSelecionadoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 180, 30));

        labelSeleccioneItem.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelSeleccioneItem.setForeground(new java.awt.Color(204, 0, 0));
        labelSeleccioneItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSeleccioneItem.setText("<html><body>seleccione un producto por favor.</html></body>");
        jPanel1.add(labelSeleccioneItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 630, 180, 20));

        botonActualizarVenta.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarVenta.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        botonActualizarVenta.setForeground(new java.awt.Color(51, 51, 51));
        botonActualizarVenta.setText("<html><body>Actualizar venta</body></html>");
        botonActualizarVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonActualizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonActualizarVenta.setFocusable(false);
        jPanel1.add(botonActualizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 600, 110, 30));

        labelBloqueTabla.setBackground(new java.awt.Color(255, 255, 255));
        labelBloqueTabla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(labelBloqueTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 910, 450));

        labelSigno3.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno3.setFont(new java.awt.Font("Leelawadee", 0, 12)); // NOI18N
        labelSigno3.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno3.setText("%");
        labelSigno3.setBorder(null);
        labelSigno3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 30, 20));

        labelSigno4.setBackground(new java.awt.Color(255, 255, 255));
        labelSigno4.setFont(new java.awt.Font("Leelawadee", 0, 10)); // NOI18N
        labelSigno4.setForeground(new java.awt.Color(51, 51, 51));
        labelSigno4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        labelSigno4.setText("%");
        labelSigno4.setBorder(null);
        labelSigno4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(labelSigno4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 160, 20, 20));

        panelimagenes.setOpaque(false);

        javax.swing.GroupLayout panelimagenesLayout = new javax.swing.GroupLayout(panelimagenes);
        panelimagenes.setLayout(panelimagenesLayout);
        panelimagenesLayout.setHorizontalGroup(
            panelimagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelimagenesLayout.setVerticalGroup(
            panelimagenesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel1.add(panelimagenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 300, 300));

        labelReloj.setFont(new java.awt.Font("Leelawadee", 0, 18)); // NOI18N
        labelReloj.setForeground(new java.awt.Color(0, 0, 0));
        labelReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReloj.setText("Reloj");
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        labelReloj.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
        jPanel1.add(labelReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 110, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Imagenes/FondoVentanaPrincipalFULL.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1457, 815));

        barraMenu.setBackground(new java.awt.Color(255, 255, 255));
        barraMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        menuArchivo.setBackground(new java.awt.Color(255, 255, 255));
        menuArchivo.setBorder(null);
        menuArchivo.setForeground(new java.awt.Color(102, 102, 102));
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        menuItemCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        menuItemCerrarSesion.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        menuItemCerrarSesion.setForeground(new java.awt.Color(102, 102, 102));
        menuItemCerrarSesion.setText("Cerrar sesion");
        menuItemCerrarSesion.setBorder(null);
        menuArchivo.add(menuItemCerrarSesion);

        menuItemSalir.setBackground(new java.awt.Color(255, 255, 255));
        menuItemSalir.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        menuItemSalir.setForeground(new java.awt.Color(102, 102, 102));
        menuItemSalir.setText("Salir");
        menuItemSalir.setBorder(null);
        menuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuItemSalir);

        barraMenu.add(menuArchivo);

        menuGestionar.setBackground(new java.awt.Color(255, 255, 255));
        menuGestionar.setBorder(null);
        menuGestionar.setForeground(new java.awt.Color(102, 102, 102));
        menuGestionar.setText("Gestionar");
        menuGestionar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemGestionarMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        itemGestionarMedicamentos.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemGestionarMedicamentos.setForeground(new java.awt.Color(102, 102, 102));
        itemGestionarMedicamentos.setText("Medicamentos");
        itemGestionarMedicamentos.setBorder(null);
        menuGestionar.add(itemGestionarMedicamentos);

        itemGestionarProveedores.setBackground(new java.awt.Color(255, 255, 255));
        itemGestionarProveedores.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemGestionarProveedores.setForeground(new java.awt.Color(102, 102, 102));
        itemGestionarProveedores.setText("Proveedores");
        itemGestionarProveedores.setBorder(null);
        itemGestionarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionarProveedoresActionPerformed(evt);
            }
        });
        menuGestionar.add(itemGestionarProveedores);

        itemGestionarLaboratorios.setBackground(new java.awt.Color(255, 255, 255));
        itemGestionarLaboratorios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemGestionarLaboratorios.setForeground(new java.awt.Color(102, 102, 102));
        itemGestionarLaboratorios.setText("Laboratorios");
        itemGestionarLaboratorios.setBorder(null);
        menuGestionar.add(itemGestionarLaboratorios);

        itemGestionarClientes.setBackground(new java.awt.Color(255, 255, 255));
        itemGestionarClientes.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemGestionarClientes.setForeground(new java.awt.Color(102, 102, 102));
        itemGestionarClientes.setText("Clientes");
        itemGestionarClientes.setBorder(null);
        menuGestionar.add(itemGestionarClientes);

        barraMenu.add(menuGestionar);

        MenuRealizar.setBackground(new java.awt.Color(255, 255, 255));
        MenuRealizar.setBorder(null);
        MenuRealizar.setForeground(new java.awt.Color(102, 102, 102));
        MenuRealizar.setText("Realizar");
        MenuRealizar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemRealizarVentas.setBackground(new java.awt.Color(255, 255, 255));
        itemRealizarVentas.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemRealizarVentas.setForeground(new java.awt.Color(102, 102, 102));
        itemRealizarVentas.setText("Ventas");
        itemRealizarVentas.setBorder(null);
        MenuRealizar.add(itemRealizarVentas);

        itemRealizarDevolucionesOcambio.setBackground(new java.awt.Color(255, 255, 255));
        itemRealizarDevolucionesOcambio.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemRealizarDevolucionesOcambio.setForeground(new java.awt.Color(102, 102, 102));
        itemRealizarDevolucionesOcambio.setText("Devoluciones / Cambios");
        itemRealizarDevolucionesOcambio.setBorder(null);
        MenuRealizar.add(itemRealizarDevolucionesOcambio);

        barraMenu.add(MenuRealizar);

        MenuConsultar.setBackground(new java.awt.Color(255, 255, 255));
        MenuConsultar.setBorder(null);
        MenuConsultar.setForeground(new java.awt.Color(102, 102, 102));
        MenuConsultar.setText("Consultar");
        MenuConsultar.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemConsultarMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarMedicamentos.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarMedicamentos.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarMedicamentos.setText("Medicamentos");
        itemConsultarMedicamentos.setBorder(null);
        itemConsultarMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarMedicamentosActionPerformed(evt);
            }
        });
        MenuConsultar.add(itemConsultarMedicamentos);

        itemConsultarProveedores.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarProveedores.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarProveedores.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarProveedores.setText("Proveedores");
        itemConsultarProveedores.setBorder(null);
        MenuConsultar.add(itemConsultarProveedores);

        itemConsultarLaboratorios.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarLaboratorios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarLaboratorios.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarLaboratorios.setText("Laboratorios");
        itemConsultarLaboratorios.setBorder(null);
        MenuConsultar.add(itemConsultarLaboratorios);

        itemConsultarClientes.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarClientes.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarClientes.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarClientes.setText("Clientes");
        itemConsultarClientes.setBorder(null);
        MenuConsultar.add(itemConsultarClientes);

        itemConsultarVentas.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarVentas.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarVentas.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarVentas.setText("Ventas");
        itemConsultarVentas.setBorder(null);
        MenuConsultar.add(itemConsultarVentas);

        itemConsultarFactura.setBackground(new java.awt.Color(255, 255, 255));
        itemConsultarFactura.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConsultarFactura.setForeground(new java.awt.Color(102, 102, 102));
        itemConsultarFactura.setText("Facturas");
        itemConsultarFactura.setBorder(null);
        MenuConsultar.add(itemConsultarFactura);

        barraMenu.add(MenuConsultar);

        MenuReportes.setBackground(new java.awt.Color(255, 255, 255));
        MenuReportes.setBorder(null);
        MenuReportes.setForeground(new java.awt.Color(102, 102, 102));
        MenuReportes.setText("Reportes");
        MenuReportes.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemReporteInventarioMedicamentos.setBackground(new java.awt.Color(255, 255, 255));
        itemReporteInventarioMedicamentos.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemReporteInventarioMedicamentos.setForeground(new java.awt.Color(102, 102, 102));
        itemReporteInventarioMedicamentos.setText("Inventario Medicamentos");
        itemReporteInventarioMedicamentos.setBorder(null);
        MenuReportes.add(itemReporteInventarioMedicamentos);

        itemReporteMedicamentosVencer.setBackground(new java.awt.Color(255, 255, 255));
        itemReporteMedicamentosVencer.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemReporteMedicamentosVencer.setForeground(new java.awt.Color(102, 102, 102));
        itemReporteMedicamentosVencer.setText("Medicamentos a Vencer");
        itemReporteMedicamentosVencer.setBorder(null);
        MenuReportes.add(itemReporteMedicamentosVencer);

        itemReporteDevolucionesCambios.setBackground(new java.awt.Color(255, 255, 255));
        itemReporteDevolucionesCambios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemReporteDevolucionesCambios.setForeground(new java.awt.Color(102, 102, 102));
        itemReporteDevolucionesCambios.setText("Devoluciones/ Cambios");
        itemReporteDevolucionesCambios.setBorder(null);
        MenuReportes.add(itemReporteDevolucionesCambios);

        itemReporteGeneralVentas.setBackground(new java.awt.Color(255, 255, 255));
        itemReporteGeneralVentas.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemReporteGeneralVentas.setForeground(new java.awt.Color(102, 102, 102));
        itemReporteGeneralVentas.setText("General de Ventas ");
        itemReporteGeneralVentas.setBorder(null);
        MenuReportes.add(itemReporteGeneralVentas);

        barraMenu.add(MenuReportes);

        menuAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        menuAdministrador.setBorder(null);
        menuAdministrador.setForeground(new java.awt.Color(102, 102, 102));
        menuAdministrador.setText("Administrar");
        menuAdministrador.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemGestionarFacturas.setBackground(new java.awt.Color(255, 255, 255));
        itemGestionarFacturas.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemGestionarFacturas.setForeground(new java.awt.Color(102, 102, 102));
        itemGestionarFacturas.setText("Gestionar factura");
        itemGestionarFacturas.setBorder(null);
        menuAdministrador.add(itemGestionarFacturas);

        conf_infoEmpresaClienteDelSoftware.setBackground(new java.awt.Color(255, 255, 255));
        conf_infoEmpresaClienteDelSoftware.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        conf_infoEmpresaClienteDelSoftware.setForeground(new java.awt.Color(102, 102, 102));
        conf_infoEmpresaClienteDelSoftware.setText("Conf. info Empresa");
        conf_infoEmpresaClienteDelSoftware.setBorder(null);
        menuAdministrador.add(conf_infoEmpresaClienteDelSoftware);

        itemConfIVADes.setBackground(new java.awt.Color(255, 255, 255));
        itemConfIVADes.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemConfIVADes.setForeground(new java.awt.Color(102, 102, 102));
        itemConfIVADes.setText("Conf. valores Iva y Desc.");
        itemConfIVADes.setBorder(null);
        menuAdministrador.add(itemConfIVADes);

        jMenuItem25.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem25.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        jMenuItem25.setForeground(new java.awt.Color(102, 102, 102));
        jMenuItem25.setText("Rangos de Facturacion");
        jMenuItem25.setBorder(null);
        jMenuItem25.setEnabled(false);
        menuAdministrador.add(jMenuItem25);

        subMenuCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        subMenuCrearUsuario.setBorder(null);
        subMenuCrearUsuario.setForeground(new java.awt.Color(102, 102, 102));
        subMenuCrearUsuario.setText("Gestionar Usuarios");
        subMenuCrearUsuario.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N

        itemCrearUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        itemCrearUsuarios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemCrearUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        itemCrearUsuarios.setText("Crear Usuarios");
        itemCrearUsuarios.setBorder(null);
        subMenuCrearUsuario.add(itemCrearUsuarios);

        itemBuscarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        itemBuscarUsuarios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemBuscarUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        itemBuscarUsuarios.setText("Buscar info. Usuarios");
        itemBuscarUsuarios.setBorder(null);
        subMenuCrearUsuario.add(itemBuscarUsuarios);

        itemEditarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        itemEditarUsuarios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemEditarUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        itemEditarUsuarios.setText("Editar Usuarios");
        itemEditarUsuarios.setBorder(null);
        subMenuCrearUsuario.add(itemEditarUsuarios);

        itemEliminarUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        itemEliminarUsuarios.setFont(new java.awt.Font("Leelawadee", 0, 14)); // NOI18N
        itemEliminarUsuarios.setForeground(new java.awt.Color(102, 102, 102));
        itemEliminarUsuarios.setText("Eliminar Usuarios");
        itemEliminarUsuarios.setBorder(null);
        subMenuCrearUsuario.add(itemEliminarUsuarios);

        menuAdministrador.add(subMenuCrearUsuario);

        barraMenu.add(menuAdministrador);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void itemGestionarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionarProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemGestionarProveedoresActionPerformed

    private void itemConsultarMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarMedicamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarMedicamentosActionPerformed

    private void menuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSalirActionPerformed

    }//GEN-LAST:event_menuItemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuConsultar;
    public javax.swing.JMenu MenuRealizar;
    public javax.swing.JMenu MenuReportes;
    public javax.swing.JMenuBar barraMenu;
    public javax.swing.JButton botonActualizarVenta;
    public javax.swing.JLabel botonBorrar;
    public javax.swing.JButton botonCancelarMod;
    public javax.swing.JButton botonCerrarCaja;
    public javax.swing.JButton botonEliminarDetalle;
    public javax.swing.JButton botonFacturar;
    public javax.swing.JButton botonLimpiarVenta;
    public javax.swing.JButton botonModificarDetalle;
    public javax.swing.JButton botonModificarVenta;
    public javax.swing.JLabel botonOk;
    public javax.swing.JTextField cajaAtiende;
    public javax.swing.JTextField cajaCantidadDetalle;
    public javax.swing.JTextField cajaCantidadDetalleAModificar;
    public javax.swing.JTextField cajaCliente;
    public javax.swing.JTextField cajaCodigoBarras;
    public javax.swing.JTextField cajaDescuentoAModificar;
    public javax.swing.JTextField cajaIngresarDescuento;
    public javax.swing.JTextField cajaIngresarIVA;
    public javax.swing.JTextField cajaSubtotal;
    public javax.swing.JTextField cajaTotal;
    public javax.swing.JTextField caja_IvaModificar;
    public javax.swing.JTextField caja_IvaTotal;
    public javax.swing.JMenuItem conf_infoEmpresaClienteDelSoftware;
    public javax.swing.JMenuItem itemBuscarUsuarios;
    public javax.swing.JMenuItem itemConfIVADes;
    public javax.swing.JMenuItem itemConsultarClientes;
    public javax.swing.JMenuItem itemConsultarFactura;
    public javax.swing.JMenuItem itemConsultarLaboratorios;
    public javax.swing.JMenuItem itemConsultarMedicamentos;
    public javax.swing.JMenuItem itemConsultarProveedores;
    public javax.swing.JMenuItem itemConsultarVentas;
    public javax.swing.JMenuItem itemCrearUsuarios;
    public javax.swing.JMenuItem itemEditarUsuarios;
    public javax.swing.JMenuItem itemEliminarUsuarios;
    public javax.swing.JMenuItem itemGestionarClientes;
    public javax.swing.JMenuItem itemGestionarFacturas;
    public javax.swing.JMenuItem itemGestionarLaboratorios;
    public javax.swing.JMenuItem itemGestionarMedicamentos;
    public javax.swing.JMenuItem itemGestionarProveedores;
    public javax.swing.JMenuItem itemRealizarDevolucionesOcambio;
    public javax.swing.JMenuItem itemRealizarVentas;
    public javax.swing.JMenuItem itemReporteDevolucionesCambios;
    public javax.swing.JMenuItem itemReporteGeneralVentas;
    public javax.swing.JMenuItem itemReporteInventarioMedicamentos;
    public javax.swing.JMenuItem itemReporteMedicamentosVencer;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JMenuItem jMenuItem25;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel labelAtiende;
    public javax.swing.JLabel labelBloqueBotonesParaDetalle;
    public javax.swing.JLabel labelBloqueIngresar;
    public javax.swing.JLabel labelBloqueModificar;
    public javax.swing.JLabel labelBloqueTabla;
    public javax.swing.JLabel labelCantidad;
    public javax.swing.JLabel labelCantidadAModificar;
    public javax.swing.JLabel labelCantidadenStock;
    public javax.swing.JLabel labelCargo;
    public javax.swing.JLabel labelCliente;
    public javax.swing.JLabel labelClienteAMostrar;
    public javax.swing.JLabel labelClienteNoRegistrado;
    public javax.swing.JLabel labelConfirmaClienteEnDB;
    public javax.swing.JLabel labelDescuento;
    public javax.swing.JLabel labelDescuentoAModificar;
    public javax.swing.JLabel labelImagenProducto;
    public javax.swing.JLabel labelMostrarClienteEncontrado;
    public javax.swing.JLabel labelNombreProductoSelecionadoTabla;
    public javax.swing.JLabel labelReloj;
    public javax.swing.JLabel labelSeleccioneItem;
    public javax.swing.JTextField labelSigno1;
    public javax.swing.JTextField labelSigno2;
    public javax.swing.JTextField labelSigno3;
    public javax.swing.JTextField labelSigno4;
    public javax.swing.JTextField labelSigno5;
    public javax.swing.JTextField labelSigno6;
    public javax.swing.JTextField labelSigno7;
    public javax.swing.JLabel labelStock;
    public javax.swing.JLabel labelSubtotal;
    public javax.swing.JLabel labelTotal;
    public javax.swing.JLabel labelUsuarioActivo;
    public javax.swing.JLabel label_IvaModificar;
    public javax.swing.JLabel label_IvaTotal;
    public javax.swing.JLabel labelimagenCodigobarras;
    public javax.swing.JLabel labelingresarIVA;
    public javax.swing.JLabel labelproductoSelecionadoTabla;
    public javax.swing.JMenu menuAdministrador;
    public javax.swing.JMenu menuArchivo;
    public javax.swing.JMenu menuGestionar;
    public javax.swing.JMenuItem menuItemCerrarSesion;
    public javax.swing.JMenuItem menuItemSalir;
    public javax.swing.JPanel panelimagenes;
    public javax.swing.JMenu subMenuCrearUsuario;
    public javax.swing.JTable tablaDetalleFactura;
    // End of variables declaration//GEN-END:variables
}
